version: "3.7"

networks:
  playground-net:
    external: true

services:

  postgres11:
    build:
      context: ./11
      dockerfile: Dockerfile
    networks:
      - playground-net
    ports:
      - 5432:5432
    environment: # https://github.com/docker-library/docs/tree/master/postgres#environment-variables
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    labels:
      - 'traefik.enable=false'