version: "3.7"

networks:
  playground-net:
    external: true

services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    labels:
      - "traefik.http.routers.zipkin.rule=PathPrefix(`/zipkin/`)"
      - "traefik.http.services.zipkin.loadbalancer.server.port=9411"
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/master/zipkin-server#environment-variables
    environment:
      - STORAGE_TYPE=mem
